server.port: 8080

management:
  health:
    defaults.enabled: true
    diskspace.enabled: false
  endpoints:
    web:
      base-path: /
      exposure.include: "*"
  endpoint:
    prometheus:
      enabled: true
    health:
      enabled: true
      show-details: never
    auditevents.enabled: false
  metrics:
    tags:
      application: ${spring.application.name}
      enable.jvm: true
      enable.jvm.gc.pause: true
      enable.jvm.memory: true
      enable.jvm.threads: true
      enable.process: true
      enable.process.files: true
      enable.http: true
      enable.http.server.requests: true
      enable.logback: true
      enable.system: true
  prometheus:
    metrics:
      export:
        enabled: true

spring:
  application:
    name: engine
  kafka:
    bootstrap-servers: "0.0.0.0:29092"
    producer:
      retries: 3
      acks: all
      key-serializer: org.springframework.kafka.support.serializer.StringOrBytesSerializer
      value-serializer: org.springframework.kafka.support.serializer.JsonSerializer
#      properties:
#          - spring.json.add.type.headers: false
#          - spring.json.type.mapping: WonderSeekerLocationUpdate:statefull.geofencing.faas.common.dto.WonderSeekerLocationUpdate
    consumer:
      group-id: ${spring.application.name}
      auto-offset-reset: earliest
      key-deserializer: org.apache.kafka.common.serialization.StringDeserializer
      value-deserializer: org.springframework.kafka.support.serializer.JsonDeserializer
      properties:
          spring.json.trusted.packages: "*"



kafka:
  topic:
    config:
      event: '1:1'
      changelog: '1:1'
      messageEvents: '1:1'

game:
  engine:
    gameEventsTopic: ${GAME_EVENTS_TOPIC}
    player-a-commands-topic: ${PLAYER_A_COMMANDS_TOPIC}
    player-b-commands-topic: ${PLAYER_B_COMMANDS_TOPIC}
    gameId: ${GAME_ID}
    playerBId: ${PLAYER_B_ID}
    playerAId: ${PLAYER_A_ID}

---
spring:
  config:
    activate:
      on-profile: local

game:
  engine:
    game-events-topic: "game-events"
    player-a-commands-topic: "player-a-commands"
    player-b-commands-topic: "player-b-commands"
    game-id: "game-1"
    player-a-id: "tankA"
    player-b-id: "tankB"
