server.port: 9091

management:
  health:
    defaults.enabled: true
    diskspace.enabled: false
  endpoints:
    web:
      base-path: /
      exposure.include: "*"
  endpoint:
    prometheus:
      enabled: true
    health:
      enabled: true
      show-details: never
    auditevents.enabled: false
  metrics:
    tags:
      application: ${spring.application.name}
      enable.jvm: true
      enable.jvm.gc.pause: true
      enable.jvm.memory: true
      enable.jvm.threads: true
      enable.process: true
      enable.process.files: true
      enable.http: true
      enable.http.server.requests: true
      enable.logback: true
      enable.system: true
  prometheus:
    metrics:
      export:
        enabled: true

spring:
  application:
    name: leaderboard
  kafka:
    bootstrap-servers: "0.0.0.0:29092"
    producer:
      retries: 3
      acks: all
      key-serializer: org.springframework.kafka.support.serializer.StringOrBytesSerializer
      value-serializer: org.springframework.kafka.support.serializer.JsonSerializer
    consumer:
      group-id: ${spring.application.name}
      auto-offset-reset: earliest

game:
  leaderboard:
    game-events-topic: ${GAME_EVENTS_TOPIC}
    game-engine-host: ${GAME_ENGINE_HOST}


kafka:
  topic:
    config:
      event: '1:1'
      changelog: '1:1'
      messageEvents: '1:1'

  streams:
    server:
      config:
        app-ip: ${GAME_LEADERBOARD_HOST}
        app-port: ${server.port}


---
spring:
  config:
    activate:
      on-profile: local
  kafka:
    streams:
      replication-factor: 1
      properties:
        num.stream.threads: 1
game:
  leaderboard:
    game-events-topic: "game-events"
    game-engine-host: "http://localhost:8080"

kafka:
  streams:
    server:
      config:
        app-ip: localhost
        app-port: ${server.port}
